export const genreMap: Record<string, string> = {
  history: 'Исторический',
  horror: 'Ужасы',
  scifi: 'Научная фантастика',
  'stand-up': 'Стендап',
  fantasy: 'Фэнтези',
  drama: 'Драма',
  mystery: 'Мистика',
  family: 'Семейный',
  comedy: 'Комедия',
  romance: 'Романтика',
  music: 'Музыка',
  crime: 'Криминал',
  'tv-movie': 'ТВ фильм',
  documentary: 'Документальный',
  action: 'Боевик',
  thriller: 'Триллер',
  western: 'Вестерн',
  animation: 'Анимация',
  war: 'Военный',
  adventure: 'Приключения',
} as const
